---
packer_build: false
use_hashicorp_repository: false

# only supported when using the HashiCorp repository
enterprise: false

vault_ansible_group: 'vault'

vault_user: 'vault'
vault_group: 'vault'
vault_create_account: true

vault_home_directory: '/etc/vault.d'
vault_data_directory: '/opt/vault'
vault_install_directory: '/usr/bin'
vault_tls_directory: '{{ vault_home_directory }}/tls'
vault_license_directory: '{{ vault_home_directory }}'
vault_config_file: '{{ vault_home_directory }}/config.hcl'

vault_enable_plugins: false
vault_plugin_directory: '{{ vault_data_directory }}/plugins'

vault_architecture_map:
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64

vault_version: '1.12.3+ent'
vault_os: '{{ ansible_system|lower }}'
vault_architecture: '{{ vault_architecture_map[ansible_architecture] }}'
vault_archive: 'vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip'
vault_download: 'https://releases.hashicorp.com/vault/{{ vault_version }}/{{ vault_archive }}'

vault_client_addr: '0.0.0.0'
vault_http_port: '8200'
vault_api_port: '8201'
vault_ui_enable: true

# options: none, gce, azure, aws
cloud:
  provider: 'none'

# options: file, integrated, consul
vault_storage_backend: 'integrated'

vault_seal:
  type: 'shamir'

vault_tls_disable_client_certs: true