- name: Copying TLS certificates
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ vault_tls_directory }}/{{ item | basename }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0400'
  with_items:
    - '{{ vault_tls_ca_cert_file | default([]) }}'
    - '{{ vault_tls_cert_file }}'
    - '{{ vault_tls_key_file }}'
  when:
    - vault_tls_cert_file is defined
    - vault_tls_key_file is defined
  notify:
    - Restart Vault

- name: Copying Vault license file
  ansible.builtin.copy:
    src: '{{ vault_license_file }}'
    dest: '{{ vault_license_directory }}/{{ vault_license_file | basename }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0400'
  when:
    - vault_license_file is defined

- name: Templating out Vault configuration
  ansible.builtin.template:
    src: config.hcl.j2
    dest: '{{ vault_config_file }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0660'
  #notify:
  #  - Restart Vault

- name: Templating out systemd script
  ansible.builtin.template:
    src: vault.systemd.j2
    dest: /lib/systemd/system/vault.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload Vault daemon

- name: Starting and enabling Vault
  ansible.builtin.systemd:
    name: vault
    enabled: true
    state: started