---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance01
    groups:
      - vault
    image: geerlingguy/docker-centos8-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: instance02
    groups:
      - vault
    image: geerlingguy/docker-centos8-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      vault:
        vault_storage_backend: 'integrated'
        vault_tls_ca_cert_file: 'tls/ca.pem'
        vault_tls_cert_file: 'tls/cert.pem'
        vault_tls_key_file: 'tls/key.pem'
        vault_tls_disable_client_certs: false 
verifier:
  name: ansible
